package eu.rigeldev.uirig.view

import eu.rigeldev.uirig.core.UiAppControl
import eu.rigeldev.uirig.snabbdom.modules.On
import org.w3c.dom.DragEvent
import org.w3c.dom.ErrorEvent
import org.w3c.dom.events.*

class DslOn {
    var abort : OnAbort? = null
    var activate : OnActivate? = null
    var beforeActivate : OnBeforeActivate? = null
    var beforeCopy : OnBeforeCopy? = null
    var beforeCut : OnBeforeCut? = null
    var beforeDeActivate : OnBeforeDeActivate? = null
    var beforePaste : OnBeforePaste? = null
    var blur : OnBlur? = null
    var canPlay : OnCanPlay? = null
    var canPlayThrough : OnCanPlayThrough? = null
    var change : OnChange? = null
    var click : OnClick? = null;
    var contextMenu : OnContextMenu? = null
    var copy : OnCopy? = null
    var cueChange : OnCueChange? = null
    var cut : OnCut? = null
    var doubleClick : OnDoubleClick? = null
    var deActivate : OnDeActivate? = null
    var drag : OnDrag? = null
    var dragEnd : OnDragEnd? = null
    var dragEnter : OnDragEnter? = null
    var dragLeave : OnDragLeave? = null
    var dragOver : OnDragOver? = null
    var dragStart : OnDragStart? = null
    var drop : OnDrop? = null
    var durationChange : OnDurationChange? = null
    var emptied : OnEmptied? = null
    var ended : OnEnded? = null
    var error : OnError? = null
    var focus : OnFocus? = null
    var input : OnInput? = null
    var invalid : OnInvalid? = null
    var keyDown : OnKeyDown? = null
    var keyPress : OnKeyPress? = null
    var keyUp : OnKeyUp? = null
    var load : OnLoad? = null
    var loadedData : OnLoadedData? = null
    var loadedMetaData : OnLoadedMetaData? = null
    var loadStart : OnLoadStart? = null
    var mouseDown : OnMouseDown? = null
    var mouseEnter : OnMouseEnter? = null
    var mouseLeave : OnMouseLeave? = null
    var mouseMove : OnMouseMove? = null
    var mouseOut : OnMouseOut? = null
    var mouseOver : OnMouseOver? = null
    var mouseUp : OnMouseUp? = null
    var mouseWheel : OnMouseWheel? = null
    var paste : OnPaste? = null
    var pause : OnPause? = null
    var play : OnPlay? = null
    var playing : OnPlaying? = null
    var progress : OnProgress? = null
    var rateChange : OnRateChange? = null
    var reset : OnReset? = null
    var scroll : OnScroll? = null
    var seeked : OnSeeked? = null
    var seeking : OnSeeking? = null
    var select : OnSelect? = null
    var selectStart : OnSelectStart? = null
    var stalled : OnStalled? = null
    var submit : OnSubmit? = null
    var suspend : OnSuspend? = null
    var timeUpdate : OnTimeUpdate? = null
    var volumeChange : OnVolumeChange? = null
    var waiting : OnWaiting? = null
    var ariaRequest : OnAriaRequest? = null
    var command : OnCommand? = null
    var gotPointerCapture : OnGotPointerCapture? = null
    var lostPointerCapture : OnLostPointerCapture? = null
    var touchCancel : OnTouchCancel? = null
    var touchEnd : OnTouchEnd? = null
    var touchMove : OnTouchMove? = null
    var touchStart : OnTouchStart? = null
    var webKitFullScreenChange : OnWebKitFullScreenChange? = null
    var webKitFullScreenError : OnWebKitFullScreenError? = null
    var pointerCancel : OnPointerCancel? = null
    var pointerDown : OnPointerDown? = null
    var pointerEnter : OnPointerEnter? = null
    var pointerLeave : OnPointerLeave? = null
    var pointerMove : OnPointerMove? = null
    var pointerOut : OnPointerOut? = null
    var pointerOver : OnPointerOver? = null
    var pointerUp : OnPointerUp? = null
    var wheel : OnWheel? = null
    var msManipulationStateChanged : OnMsManipulationStateChanged? = null
    var msContentZoom : OnMsContentZoom? = null
    var msGestureChange : OnMsGestureChange? = null
    var msGestureDoubleTap : OnMsGestureDoubleTap? = null
    var msGestureEnd : OnMsGestureEnd? = null
    var msGestureHold : OnMsGestureHold? = null
    var msGestureStart : OnMsGestureStart? = null
    var msGestureTap : OnMsGestureTap? = null
    var msGotPointerCapture : OnMsGotPointerCapture? = null
    var msInertiaStart : OnMsInertiaStart? = null
    var msLostPointerCapture : OnMsLostPointerCapture? = null
    var msPointerCancel : OnMsPointerCancel? = null
    var msPointerDown : OnMsPointerDown? = null
    var msPointerEnter : OnMsPointerEnter? = null
    var msPointerLeave : OnMsPointerLeave? = null
    var msPointerMove : OnMsPointerMove? = null
    var msPointerOut : OnMsPointerOut? = null
    var msPointerOver : OnMsPointerOver? = null
    var msPointerUp : OnMsPointerUp? = null

    fun prepare(control: UiAppControl, vNodeDataOn: On?) {
        if (vNodeDataOn != null) {
            vNodeDataOn.abort = this.createHandler(control, this.abort)
            vNodeDataOn.activate = this.createHandler(control, this.activate)
            vNodeDataOn.beforeactivate = this.createHandler(control, this.beforeActivate)
            vNodeDataOn.beforecopy = this.createHandler(control, this.beforeCopy)
            vNodeDataOn.beforecut = this.createHandler(control, this.beforeCut)
            vNodeDataOn.beforedeactivate = this.createHandler(control, this.beforeDeActivate)
            vNodeDataOn.beforepaste = this.createHandler(control, this.beforePaste)
            vNodeDataOn.blur = this.createHandler(control, this.blur)
            vNodeDataOn.canplay = this.createHandler(control, this.canPlay)
            vNodeDataOn.canplaythrough = this.createHandler(control, this.canPlayThrough)
            vNodeDataOn.click = this.createHandler(control, this.click)
            vNodeDataOn.change = this.createHandler(control, this.change)
            vNodeDataOn.contextmenu = this.createHandler(control, this.contextMenu)
            vNodeDataOn.copy = this.createHandler(control, this.copy)
            vNodeDataOn.cuechange = this.createHandler(control, this.cueChange)
            vNodeDataOn.cut = this.createHandler(control, this.cut)
            vNodeDataOn.dblclick = this.createHandler(control, this.doubleClick)
            vNodeDataOn.deactivate = this.createHandler(control, this.deActivate)
            vNodeDataOn.drag = this.createHandler(control, this.drag)
            vNodeDataOn.dragend = this.createHandler(control, this.dragEnd)
            vNodeDataOn.dragenter = this.createHandler(control, this.dragEnter)
            vNodeDataOn.dragleave = this.createHandler(control, this.dragLeave)
            vNodeDataOn.dragover = this.createHandler(control, this.dragOver)
            vNodeDataOn.dragstart = this.createHandler(control, this.dragStart)
            vNodeDataOn.drop = this.createHandler(control, this.drop)
            vNodeDataOn.durationchange = this.createHandler(control, this.durationChange)
            vNodeDataOn.emptied = this.createHandler(control, this.emptied)
            vNodeDataOn.ended = this.createHandler(control, this.ended)
            vNodeDataOn.error = this.createHandler(control, this.error)
            vNodeDataOn.focus = this.createHandler(control, this.focus)
            vNodeDataOn.input = this.createHandler(control, this.input)
            vNodeDataOn.invalid = this.createHandler(control, this.invalid)
            vNodeDataOn.keydown = this.createHandler(control, this.keyDown)
            vNodeDataOn.keypress = this.createHandler(control, this.keyPress)
            vNodeDataOn.keyup = this.createHandler(control, this.keyUp)
            vNodeDataOn.load = this.createHandler(control, this.load)
            vNodeDataOn.loadeddata = this.createHandler(control, this.loadedData)
            vNodeDataOn.loadedmetadata = this.createHandler(control, this.loadedMetaData)
            vNodeDataOn.loadstart = this.createHandler(control, this.loadStart)
            vNodeDataOn.mousedown = this.createHandler(control, this.mouseDown)
            vNodeDataOn.mouseenter = this.createHandler(control, this.mouseEnter)
            vNodeDataOn.mouseleave = this.createHandler(control, this.mouseLeave)
            vNodeDataOn.mousemove = this.createHandler(control, this.mouseMove)
            vNodeDataOn.mouseout = this.createHandler(control, this.mouseOut)
            vNodeDataOn.mouseover = this.createHandler(control, this.mouseOver)
            vNodeDataOn.mouseup = this.createHandler(control, this.mouseUp)
            vNodeDataOn.mousewheel = this.createHandler(control, this.mouseWheel)
            vNodeDataOn.paste = this.createHandler(control, this.paste)
            vNodeDataOn.pause = this.createHandler(control, this.pause)
            vNodeDataOn.play = this.createHandler(control, this.play)
            vNodeDataOn.playing = this.createHandler(control, this.playing)
            vNodeDataOn.progress = this.createHandler(control, this.progress)
            vNodeDataOn.ratechange = this.createHandler(control, this.rateChange)
            vNodeDataOn.reset = this.createHandler(control, this.reset)
            vNodeDataOn.scroll = this.createHandler(control, this.scroll)
            vNodeDataOn.seeked = this.createHandler(control, this.seeked)
            vNodeDataOn.seeking = this.createHandler(control, this.seeking)
            vNodeDataOn.select = this.createHandler(control, this.select)
            vNodeDataOn.selectstart = this.createHandler(control, this.selectStart)
            vNodeDataOn.stalled = this.createHandler(control, this.stalled)
            vNodeDataOn.submit = this.createHandler(control, this.submit)
            vNodeDataOn.suspend = this.createHandler(control, this.suspend)
            vNodeDataOn.timeupdate = this.createHandler(control, this.timeUpdate)
            vNodeDataOn.volumechange = this.createHandler(control, this.volumeChange)
            vNodeDataOn.waiting = this.createHandler(control, this.waiting)
            vNodeDataOn.ariarequest = this.createHandler(control, this.ariaRequest)
            vNodeDataOn.command = this.createHandler(control, this.command)
            vNodeDataOn.gotpointercapture = this.createHandler(control, this.gotPointerCapture)
            vNodeDataOn.lostpointercapture = this.createHandler(control, this.lostPointerCapture)
            vNodeDataOn.touchcancel = this.createHandler(control, this.touchCancel)
            vNodeDataOn.touchend = this.createHandler(control, this.touchEnd)
            vNodeDataOn.touchmove = this.createHandler(control, this.touchMove)
            vNodeDataOn.touchstart = this.createHandler(control, this.touchStart)
            vNodeDataOn.webkitfullscreenchange = this.createHandler(control, this.webKitFullScreenChange)
            vNodeDataOn.webkitfullscreenerror = this.createHandler(control, this.webKitFullScreenError)
            vNodeDataOn.pointercancel = this.createHandler(control, this.pointerCancel)
            vNodeDataOn.pointerdown = this.createHandler(control, this.pointerDown)
            vNodeDataOn.pointerenter = this.createHandler(control, this.pointerEnter)
            vNodeDataOn.pointerleave = this.createHandler(control, this.pointerLeave)
            vNodeDataOn.pointermove = this.createHandler(control, this.pointerMove)
            vNodeDataOn.pointerout = this.createHandler(control, this.pointerOut)
            vNodeDataOn.pointerover = this.createHandler(control, this.pointerOver)
            vNodeDataOn.pointerup = this.createHandler(control, this.pointerUp)
            vNodeDataOn.wheel = this.createHandler(control, this.wheel)
            vNodeDataOn.MSManipulationStateChanged = this.createHandler(control, this.msManipulationStateChanged)
            vNodeDataOn.MSContentZoom = this.createHandler(control, this.msContentZoom)
            vNodeDataOn.MSGestureChange = this.createHandler(control, this.msGestureChange)
            vNodeDataOn.MSGestureDoubleTap = this.createHandler(control, this.msGestureDoubleTap)
            vNodeDataOn.MSGestureEnd = this.createHandler(control, this.msGestureEnd)
            vNodeDataOn.MSGestureHold = this.createHandler(control, this.msGestureHold)
            vNodeDataOn.MSGestureStart = this.createHandler(control, this.msGestureStart)
            vNodeDataOn.MSGestureTap = this.createHandler(control, this.msGestureTap)
            vNodeDataOn.MSGotPointerCapture = this.createHandler(control, this.msGotPointerCapture)
            vNodeDataOn.MSInertiaStart = this.createHandler(control, this.msInertiaStart)
            vNodeDataOn.MSLostPointerCapture = this.createHandler(control, this.msLostPointerCapture)
            vNodeDataOn.MSPointerCancel = this.createHandler(control, this.msPointerCancel)
            vNodeDataOn.MSPointerDown = this.createHandler(control, this.msPointerDown)
            vNodeDataOn.MSPointerEnter = this.createHandler(control, this.msPointerEnter)
            vNodeDataOn.MSPointerLeave = this.createHandler(control, this.msPointerLeave)
            vNodeDataOn.MSPointerMove = this.createHandler(control, this.msPointerMove)
            vNodeDataOn.MSPointerOut = this.createHandler(control, this.msPointerOut)
            vNodeDataOn.MSPointerOver = this.createHandler(control, this.msPointerOver)
            vNodeDataOn.MSPointerUp = this.createHandler(control, this.msPointerUp)
        }
    }

    private fun <T> createHandler(control: UiAppControl, messageCreator : ((event: T) -> Any?)?): ((T) -> Unit)? {
        if (messageCreator == null) {
            return null
        } else {
            return { event  ->
                val message = messageCreator.invoke(event)
                control.send(message)
            }
        }
    }

}

typealias OnAbort = (event : UIEvent) -> Any?
typealias OnActivate = (event: UIEvent) -> Any?
typealias OnBeforeActivate = (event: UIEvent) -> Any?
typealias OnBeforeCopy = (event: dynamic /* ClipboardEvent */) -> Any?
typealias OnBeforeCut = (event: dynamic /* ClipboardEvent */) -> Any?
typealias OnBeforeDeActivate = (event: UIEvent) -> Any?
typealias OnBeforePaste = (event: dynamic /* ClipboardEvent */) -> Any?
typealias OnBlur = (event: UIEvent) -> Any?
typealias OnCanPlay = (event: Event) -> Any?
typealias OnCanPlayThrough = (event: Event) -> Any?
typealias OnChange = (event: Event) -> Any?
typealias OnClick = (event: MouseEvent) -> Any?
typealias OnContextMenu = (event: dynamic /* PointerEvent */) -> Any?
typealias OnCopy = (event: dynamic /* ClipboardEvent */) -> Any?
typealias OnCueChange = (event: Event) -> Any?
typealias OnCut = (event: dynamic /* ClipboardEvent */) -> Any?
typealias OnDoubleClick = (event: MouseEvent) -> Any?
typealias OnDeActivate = (event: UIEvent) -> Any?
typealias OnDrag = (event: DragEvent) -> Any?
typealias OnDragEnd = (event: DragEvent) -> Any?
typealias OnDragEnter = (event: DragEvent) -> Any?
typealias OnDragLeave = (event: DragEvent) -> Any?
typealias OnDragOver = (event: DragEvent) -> Any?
typealias OnDragStart = (event: DragEvent) -> Any?
typealias OnDrop = (event: DragEvent) -> Any?
typealias OnDurationChange = (event: Event) -> Any?
typealias OnEmptied = (event: Event) -> Any?
typealias OnEnded = (event: dynamic /* MediaStreamErrorEvent */) -> Any?
typealias OnError = (event: ErrorEvent) -> Any?
typealias OnFocus = (event: FocusEvent) -> Any?
typealias OnInput = (event: Event) -> Any?
typealias OnInvalid = (event: Event) -> Any?
typealias OnKeyDown = (event: KeyboardEvent) -> Any?
typealias OnKeyPress = (event: KeyboardEvent) -> Any?
typealias OnKeyUp = (event: KeyboardEvent) -> Any?
typealias OnLoad = (event: Event) -> Any?
typealias OnLoadedData = (event: Event) -> Any?
typealias OnLoadedMetaData = (event: Event) -> Any?
typealias OnLoadStart = (event: Event) -> Any?
typealias OnMouseDown = (event: MouseEvent) -> Any?
typealias OnMouseEnter = (event: MouseEvent) -> Any?
typealias OnMouseLeave = (event: MouseEvent) -> Any?
typealias OnMouseMove = (event: MouseEvent) -> Any?
typealias OnMouseOut = (event: MouseEvent) -> Any?
typealias OnMouseOver = (event: MouseEvent) -> Any?
typealias OnMouseUp = (event: MouseEvent) -> Any?
typealias OnMouseWheel = (event: WheelEvent) -> Any?
typealias OnPaste = (event: dynamic /* ClipboardEvent */) -> Any?
typealias OnPause = (event: Event) -> Any?
typealias OnPlay = (event: Event) -> Any?
typealias OnPlaying = (event: Event) -> Any?
typealias OnProgress = (event: Event) -> Any?
typealias OnRateChange = (event: Event) -> Any?
typealias OnReset = (event: Event) -> Any?
typealias OnScroll = (event: UIEvent) -> Any?
typealias OnSeeked = (event: Event) -> Any?
typealias OnSeeking = (event: Event) -> Any?
typealias OnSelect = (event: UIEvent) -> Any?
typealias OnSelectStart = (event: Event) -> Any?
typealias OnStalled = (event: Event) -> Any?
typealias OnSubmit = (event: Event) -> Any?
typealias OnSuspend = (event: Event) -> Any?
typealias OnTimeUpdate = (event: Event) -> Any?
typealias OnVolumeChange = (event: Event) -> Any?
typealias OnWaiting = (event: Event) -> Any?
typealias OnAriaRequest = (event: Event) -> Any?
typealias OnCommand = (event: Event) -> Any?
typealias OnGotPointerCapture = (event: dynamic /* PointerEvent */) -> Any?
typealias OnLostPointerCapture = (event: dynamic /* PointerEvent */) -> Any?
typealias OnTouchCancel = (event: dynamic /* TouchEvent */) -> Any?
typealias OnTouchEnd = (event: dynamic /* TouchEvent */) -> Any?
typealias OnTouchMove = (event: dynamic /* TouchEvent */) -> Any?
typealias OnTouchStart = (event: dynamic /* TouchEvent */) -> Any?
typealias OnWebKitFullScreenChange = (event: Event) -> Any?
typealias OnWebKitFullScreenError = (event: Event) -> Any?
typealias OnPointerCancel = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerDown = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerEnter = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerLeave = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerMove = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerOut = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerOver = (event: dynamic /* PointerEvent */) -> Any?
typealias OnPointerUp = (event: dynamic /* PointerEvent */) -> Any?
typealias OnWheel = (event: WheelEvent) -> Any?
typealias OnMsManipulationStateChanged = (event: dynamic /* MSManipulationEvent */) -> Any?
typealias OnMsContentZoom = (event: UIEvent) -> Any?
typealias OnMsGestureChange = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsGestureDoubleTap = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsGestureEnd = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsGestureHold = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsGestureStart = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsGestureTap = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsGotPointerCapture = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsInertiaStart = (event: dynamic /* MSGestureEvent */) -> Any?
typealias OnMsLostPointerCapture = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerCancel = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerDown = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerEnter = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerLeave = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerMove = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerOut = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerOver = (event: dynamic /* MSPointerEvent */) -> Any?
typealias OnMsPointerUp = (event: dynamic /* MSPointerEvent */) -> Any?

